# Generated by Django 2.1.14 on 2019-11-22 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20191121_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='address',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='beds',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='city_state',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='sq_ft',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='website',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
