# Generated by Django 2.1.14 on 2019-12-03 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rsvp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rsvp',
            old_name='name',
            new_name='title',
        ),
    ]
