# Generated by Django 2.1.14 on 2019-12-03 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20191202_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='address',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
    ]
