# Generated by Django 2.1.14 on 2019-12-03 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20191202_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
    ]
