# Generated by Django 2.1.14 on 2019-12-03 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20191202_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='name',
        ),
    ]
