# Generated by Django 2.1.14 on 2019-12-03 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20191202_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
