# Generated by Django 2.1.14 on 2019-12-03 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_rsvp_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rsvp_template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(blank='', null=True, upload_to='acquisition_images')),
            ],
        ),
    ]
