# Generated by Django 2.1.14 on 2019-12-05 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_rsvp_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp_template',
            name='image',
            field=models.ImageField(blank='', null=True, upload_to='event_images'),
        ),
    ]
