# Generated by Django 2.1.14 on 2019-12-05 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20191204_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='image',
            field=models.ImageField(blank='', null=True, upload_to='event_images'),
        ),
    ]
