# Generated by Django 2.1.14 on 2019-12-02 01:12

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('acquisition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisition',
            name='title',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('test1', 'test1'), ('test2', 'test2'), ('test3', 'test3'), ('test3', 'test4')], max_length=23),
        ),
    ]
