# Generated by Django 2.1.14 on 2019-12-02 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquisition', '0002_auto_20191201_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='acquisition',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='acquisition_images/'),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='title',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
