# Generated by Django 2.1.14 on 2019-12-02 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquisition', '0003_auto_20191201_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acquisition',
            name='image',
        ),
        migrations.AddField(
            model_name='acquisition',
            name='author',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='acquisition',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='acquisition_images/'),
        ),
    ]
