# Generated by Django 2.1.14 on 2019-12-02 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquisition', '0004_auto_20191201_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisition',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='books/pdfs/'),
        ),
    ]
